# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "artii", "~> 2.1"

gem "tty-prompt", "~> 0.23.1"

gem 'json', '~> 2.5', '>= 2.5.1'

gem 'terminal-table', '~> 3.0', '>= 3.0.1'
gem "tty-reader", "~> 0.9.0"
